name = "hono_workers_example"
compatibility_date = "2024-07-22"
send_metrics = true
compatibility_flags = ["nodejs_compat"]
logpush = true

# Cloudflare Workers R2 buckets
# r2_buckets = [
#   { binding = "HONO_WORKERS_EXAMPLE", bucket_name = "HONO_WORKERS_EXAMPLE", preview_bucket_name = "HONO_WORKERS_EXAMPLE_PREVIEW" },
# ]

# Cloudflare Workers KV namespaces
# kv_namespaces = [
#   { binding = "HONO_WORKERS_EXAMPLE", id = "HONO_WORKERS_EXAMPLE", preview_id = "HONO_WORKERS_EXAMPLE_PREVIEW" },
# ]

# Cron Events
[triggers]
crons = []

# Variables
[vars]
